[package]
name = "_15"
version = "0.1.0"
authors = ["r3drock <philipp.koppenstein@udo.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.intcomputer]
path = "../intcomputer"

[dependencies]
petgraph = "0.5.0"
